version: '3.3'
services:
  # api:
    container_name: 'api'
    build: './api'
    ports:
      - '8080:8080'
    volumes:
      - './api:/go/src/app'
    depends_on:
      - 'mongo'
  # web:
  #   container_name: 'web'
  #   image: 'nginx:latest'
  #   ports:
  #     - '8081:80'
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   volumes:
  #     - /app/node_modules
  #     - ./web:/app

    # depends_on:
    #   - 'api'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100::27017'

